# Generated by Django 4.2.7 on 2023-11-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='section',
        ),
        migrations.RemoveField(
            model_name='income',
            name='section',
        ),
    ]
